references:
  attach_workspace: &attach_workspace
    attach_workspace:
      at: ./

version: 2
jobs:
  server/install:
    docker:
      - image: circleci/node:10
    steps:
      - checkout

      - run: |
          cd server/
          npm ci

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - server/node_modules/

  server/lint:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - *attach_workspace

      - run: |
          cd server/
          npm run lint

  ui/install:
    docker:
      - image: circleci/node:10
    steps:
      - checkout

      - run: |
          npm ci

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - node_modules/

  ui/lint:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - *attach_workspace

      - run: |
          npm run lint

  ui/build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - *attach_workspace

      - run: |
          npm run build

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - build/

  prisma_deploy:
    environment:
      DEPLOY_DIR: ~/prisma_deploy
      CLEVER_CLOUD_REMOTE_HOST: push-par-clevercloud-customers.services.clever-cloud.com
      CLEVER_CLOUD_REMOTE_APP_ID: app_f9c5c1cb-fe9c-41f9-a6c0-793e8326e95b
    docker:
      - image: circleci/node:10
    steps:
      - *attach_workspace

      - add_ssh_keys:
          fingerprints:
            - "6f:f2:b4:c2:e5:13:28:f8:02:2d:da:48:34:0c:14:7f"

      - run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${CLEVER_CLOUD_REMOTE_HOST} >> ~/.ssh/known_hosts
          mkdir -p ${DEPLOY_DIR}
          cp server/prisma/Dockerfile.clever-cloud ${DEPLOY_DIR}/Dockerfile
          cd ${DEPLOY_DIR}
          git init
          git config user.email "dsi-ext@zenika"
          git config user.name "DSI Ext"
          git add .
          git commit -m "Deploy"
          git remote add clever git+ssh://git@${CLEVER_CLOUD_REMOTE_HOST}/${CLEVER_CLOUD_REMOTE_APP_ID}.git
          git push --force clever master

  deploy:
    environment:
      DEPLOY_DIR: ~/deploy
      CLEVER_CLOUD_REMOTE_HOST: push-par-clevercloud-customers.services.clever-cloud.com
      CLEVER_CLOUD_REMOTE_APP_ID: app_c61407ae-b417-4406-86ed-cfd1acf84466
    docker:
      - image: circleci/node:10
    steps:
      - *attach_workspace

      - add_ssh_keys:
          fingerprints:
            - "6f:f2:b4:c2:e5:13:28:f8:02:2d:da:48:34:0c:14:7f"

      - run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${CLEVER_CLOUD_REMOTE_HOST} >> ~/.ssh/known_hosts
          mkdir -p ${DEPLOY_DIR}
          cp -R server/* ${DEPLOY_DIR}/
          cp -R build/ ${DEPLOY_DIR}/front_build
          cd ${DEPLOY_DIR}
          cp prisma/prisma.yml scripts/prisma_deploy_all/
          cp prisma/datamodel.graphql scripts/prisma_deploy_all/
          git init
          git config user.email "dsi-ext@zenika.com"
          git config user.name "DSI Ext"
          echo "node_modules/" > .gitignore
          git add .gitignore
          git add -A
          git commit -m "Deploy"
          git remote add clever git+ssh://git@${CLEVER_CLOUD_REMOTE_HOST}/${CLEVER_CLOUD_REMOTE_APP_ID}.git
          git push --force clever master
          npm run deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - server/install
      - server/lint:
          requires:
            - server/install
      - ui/install
      - ui/lint:
          requires:
            - ui/install
      - ui/build:
          requires:
            - ui/install
      - deploy:
          requires:
            - server/lint
            - ui/lint
            - ui/build
          filters:
            branches:
              only: master
      - prisma_deploy:
          requires:
            - deploy
          filters:
            branches:
              only: master
