references:
  workspace_root: &workspace_root /home/circleci/my-workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

version: 2
jobs:
  build:
    working_directory: *workspace_root
    docker:
      - image: circleci/node:9-browsers
    steps:
      - checkout

      - restore_cache:
          keys:
            - root-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - root-

      - run: npm install

      - run: npm run lint

      - save_cache:
          paths:
            - node_modules
          key: root-{{ checksum "package-lock.json" }}

      - restore_cache:
          keys:
            - server-{{ checksum "package-lock.json" }}
            - server-

      - run: cd server && npm install && npm run lint && cd ..

      - save_cache:
          paths:
            - server/node_modules
          key: server-{{ checksum "package-lock.json" }}

      - run: npm run build

      - run: rm -rf node_modules/

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

  prisma_deploy:
    environment:
      DEPLOY_DIR: ~/prisma_deploy
    working_directory: *workspace_root
    docker:
      - image: circleci/node:9-browsers
    steps:
      - *attach_workspace

      - run: |
          mkdir -p ${DEPLOY_DIR}
          cp server/prisma/Dockerfile.clever-cloud ${DEPLOY_DIR}/Dockerfile
          cd ${DEPLOY_DIR}
          git init
          git config user.email "dsi-ext@zenika"
          git config user.name "DSI Ext"
          git add .
          git commit -m "Deploy"
          git remote add clever $CLEVER_CLOUD_PRISMA_GIT_URL
          git push --force clever master

  deploy:
    environment:
      DEPLOY_DIR: ~/deploy
      CLEVER_CLOUD_REMOTE_HOST: push-par-clevercloud-customers.services.clever-cloud.com
      CLEVER_CLOUD_REMOTE_APP_ID: app_c61407ae-b417-4406-86ed-cfd1acf84466
    working_directory: *workspace_root
    docker:
      - image: circleci/node:9-browsers
    steps:
      - *attach_workspace

      - add_ssh_keys:
          fingerprints:
            - "6f:f2:b4:c2:e5:13:28:f8:02:2d:da:48:34:0c:14:7f"

      - run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${CLEVER_CLOUD_REMOTE_HOST} >> ~/.ssh/known_hosts
          mkdir -p ${DEPLOY_DIR}
          cp -R server/* ${DEPLOY_DIR}/
          cp -R build/ ${DEPLOY_DIR}/front_build
          cd ${DEPLOY_DIR}
          cp prisma/prisma.yml prisma/scripts/deploy_all/
          cp prisma/datamodel.graphql prisma/scripts/deploy_all/
          git init
          git config user.email "dsi-ext@zenika.com"
          git config user.name "DSI Ext"
          echo "node_modules/" > .gitignore
          git add .gitignore
          git add -A
          git commit -m "Deploy"
          git remote add clever git+ssh://git@${CLEVER_CLOUD_REMOTE_HOST}/${CLEVER_CLOUD_REMOTE_APP_ID}.git
          git push --force clever master
          npm run deploy_all
          npm run algolia

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
#      - prisma_deploy:
#          requires:
#            - build
#          filters:
#            branches:
#              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
