version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:9-browsers
    steps:
      - checkout

      - restore_cache:
          keys:
          - root-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - root-

      - run: npm install

      - run: npm run lint

      - save_cache:
          paths:
            - node_modules
          key: root-{{ checksum "package-lock.json" }}

      - restore_cache:
          keys:
          - server-{{ checksum "package-lock.json" }}
          - server-

      - run: cd server && npm install

      - save_cache:
          paths:
            - server/node_modules
          key: server-{{ checksum "package-lock.json" }}

  deploy-job:
    docker:
      - image: circleci/node:9-browsers
    steps:
      - checkout

      - restore_cache:
          keys:
          - root-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - root-

      - run: npm install

      - run: npm run lint

      - save_cache:
          paths:
            - node_modules
          key: root-{{ checksum "package-lock.json" }}

      - restore_cache:
          keys:
          - server-{{ checksum "package-lock.json" }}
          - server-

      - run: cd server && npm install

      - save_cache:
          paths:
            - server/node_modules
          key: server-{{ checksum "package-lock.json" }}

      # Authenticate GCloud
      - run: echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
      - run: sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update
      - run: sudo /opt/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run: sudo /opt/google-cloud-sdk/bin/gcloud config set project $GCLOUD_APP_ID

      - run: npm run deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          filters:
            branches:
              only: master
