runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html
  secure: always


- url: /(.*)\.([a-z]{1,4})$
  static_files: \1.\2
  upload: (.*)
  secure: always

- url: /(.*)
  static_files: index.html
  secure: always
