projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoint: http://localhost:4000
      endpoints:
        default: http://localhost:4000
  prisma:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml
